config/routes.rb
Rails.application.routes.draw do
  root 'resume#homepage'
  post "/contact" => 'resume#sendMail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def homepage
  end

  def sendMail
	Pony.mail({
		  :to => 'cjcham77@gmail.com',
		  :via => :smtp,
		  :from => params[:email],
		  :subject => params[:subject],
		  :body => params[:emailbody],
		  :via_options => {
		    :address              => 'smtp.gmail.com',
		    :port                 => '587',
		    :enable_starttls_auto => true,
		    :user_name            => 'cjcham77@gmail.com',
		    :password             => ENV["EMAIL_PASSWORD"],
		    :authentication       => :plain, # :plain, :login, :cram_md5, no auth by default
		    :domain               => "carsonhamiltonresume.herokuapp.com" # the HELO domain provided by the client to the server
		  }
		})
  	# @mail = Pony.mail(:to =>'cjcham77@gmail.com', :via => :smtp, :from => params[:email], :subject => params[:subject], :body => params[:emailbody])
	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carson Hamilton Interactive Resume</title>
    <%= csrf_meta_tags %>

	<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
  </head>

  <body data-spy="scroll" data-target="#navl">
	  	<nav class="navbar navbar-inverse navbar-fixed-side resumenav">
		  <div class="container-fluid">
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1 navlist">
		      <ul class="nav navbar-nav" id="navbttn">
		        <li ><button class="buttons" id="amjump">About Me</button></li>
		        <li ><button class="buttons" id="whjump" >Work History</button></li>
		        <li ><button class="buttons" id="expjump">Experience</button></li>
		        <li ><button class="buttons" id="examplejump">Example Work</button></li>
		        <li ><button class="buttons" id="edujump">Education</button></li>
		        <li ><button class="buttons" id="cmjump">Contact Me</button></li>
		      </ul>
		    </div>
		  </div>
	 	</nav>
    <%= yield %>
  </body>
</html>

app/views/resume/_about_me.html.erb
<br>
<br>
<br>
<div class=amwrap>
	<div id="namepic">
		<div id="amname" data-aos="fade-right">
			<p data-aos="flip-up">My name is Carson Hamilton. I am 20 years old and a Junior Web Developer looking for a job in Front End web development.</p>
	</div>
	<div id="jobsearch">
		<div id="amjob" data-aos="fade-left">
			<img id="mypic" data-aos="fade-left" src="/assets/propic.jpg"></img>
		</div>
	</div>
	</div>
	<div id="hobbypic">
		<div id="amhobby" data-aos="fade-right">
			<p data-aos="flip-up">I am very skilled with both computer hardware and software. In the last year I have built 13 computers for both work and as a hobby.</p>
		</div>
	</div>
</div>

app/views/resume/_contact.html.erb
<br>
<br>
<br>
<div class="contactwrap">
	<div class="contactinfo" data-aos="fade-up-right" >
		<h2 id="contacttitle">Send me an Email</h2>
		<div id="contactform" data-aos="flip-right" data-aos-duration="1000">
			<%= form_tag(contact_path, {:class => "form"}) do %>
  				<%= email_field_tag :email, nil, :placeholder => "Your Email" %>
  				<br>
  				<%= text_field_tag :subject, nil, :placeholder => "Subject" %>
  				<br>
  				<%= text_area_tag :emailbody %>
  				<br>
  				<%= submit_tag "Send", :id=>"subbttn" %>
			<% end %>
		</div>
	</div>
	<div class="contactinfo" data-aos="fade-up-left">
		<div>
			<h2 id="cmtitle">Contact Me</h2>
		</div>
		<div id="cmline"></div>
		<div id="contacts">
			<ul id="links" data-aos="fade-left">
				<li data-aos="zoom-right" data-aos-duration="500">Phone Number: 801-928-0514</li>
				<br>
				<li data-aos="zoom-right" data-aos-duration="1000">Email Address: Cjcham77@gmail.com</li>
				<br>
				<li data-aos="zoom-right" data-aos-duration="1500">Checkout my GitHub <a href="https://github.com/Chamilton77" target="_blank">Here</a></li>
				<br>
				<li data-aos="zoom-right" data-aos-duration="2000">Here is a link to my <a href="https://www.linkedin.com/in/carson-hamilton/" target="_blank">LinkedIn</a></li>
			</ul>
		</div>
	</div>
</div>

app/views/resume/_education.html.erb
<br>
<br>
<br>
<div id="eduwrap">
	<div id="nycda" data-aos="zoom-in-right">
		<div id="nycdatitle">
			<h1>New York Code + Design Academy</h1>
			<h4 class="dates">October 2016 - January 2017</h4>
		</div>
		<div id="nycdades">
			<p>I attended the New York Code + Design Academy for a three month intesive bootcamp. During this boot camp I learned the basics of web development and how to learn new programming languages.</p>
		</div>
	</div>
	<br>
	<br>
	<br>
	<div id="college" data-aos="zoom-in">
		<div id="colltitle">
			<h1 id="collname">Strayer University</h1>
			<h4 class="dates">2015-current</h4>
		</div>
		<div id="colldes">
			<p>I am currently a student at Strayer University attending online classes and working towards a major in Business Management. I am expected to graduate in 2019.</p>
		</div>
	</div>
	<br>
	<br>
	<br>
	<div id="highschool" data-aos="zoom-in-left"">
		<h1>Syracuse High School</h1>
		<h4 class="dates">Graduated 2015</h4>
		<p>I graduated from Syracuse High School in 2015. During my senior year I was invited to join an advanced accounting class that only 24 students in the state were asked to participate.</p>
	</div>
</div>

app/views/resume/_example_work.html.erb
<br>
<br>
<br>
<div id="projects" data-aos="zoom-in">
	<div id="finalgroup" data-aos="zoom-in-right">
		<a href="https://chefwebsite.herokuapp.com/" target="_blank"><img src="/assets/chef.jpg" id="chefpic"></a> 
	</div>
	<div id="groupblog" data-aos="zoom-in-left">
		<a href="https://developerscloud.herokuapp.com/" target="_blank"><img src="/assets/devcoud.jpg" id="devcloudpic"></a>
	</div>
</div>
<div id=projdes data-aos="flip-up">
	<h3 id="projectwords">These are a couple of projects that I have worked on that show my back and front end skills. Click on the pictures to take you to the webpages.</h3>
</div>

app/views/resume/_experience.html.erb
<br>
<br> 
<br>
<div class="codexp">
	<div id="languages">
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>HTML</p></div>	
			<div class="skillword" data-aos="fade-left">
				<h4>Advanced</h4>
			</div>
			<div class="skill">
				<span style="width:90%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>CSS</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Advanced</h4>
			</div>
			<div class="skill">
				<span style="width:90%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>Bootstrap</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Beginner</h4>
			</div>
			<div class="skill">
				<span style="width:75%;" data-aos="zoom-out-right"></span>
			</div>	
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>JavaScript</p></div>	
			<div class="skillword" data-aos="fade-left">
				<h4>Intermediate</h4>
			</div>
			<div class="skill">
				<span style="width:85%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>JQuery</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Intermediate</h4>
			</div>
			<div class="skill">
				<span style="width:85%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>Ruby</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Intermediate</h4>
			</div>
			<div class="skill">
				<span style="width:85%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>Ruby On Rails</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Intermediate</h4>
			</div>
			<div class="skill">
				<span style="width:85%;" data-aos="zoom-out-right"></span>
			</div>	
		</div>
		<br>
		<div class="langlist">
			<div class="skill_name" data-aos="fade-right"><p>GitHub</p></div>
			<div class="skillword" data-aos="fade-left">
				<h4>Advanced</h4>
			</div>
			<div class="skill">
				<span style="width:90%;" data-aos="zoom-out-right"></span>
			</div>
		</div>
	</div>
</div>

app/views/resume/_mainpage.html.erb
<br>
<br>
<br>	
<div id="maintitle" data-aos="fade-left">
	<h1 id="titlename">Carson Hamilton</h1>
</div>
<div id="resumetitle" data-aos="fade-down">
	<h2 id="reactres">Junior Web Developer</h2>
</div>
<div id="instructions" data-aos="slide-up"">
	<h2 id="scrolldown">Scroll down or use the down arrow key to navigate</h2>
	<p id="arrow">&#10507;</p>
</div>

app/views/resume/_work_experience.html.erb
<br>
<br>
<br>
<br>
<div id="jobboondocks" data-aos="fade-down-right">
	<div id="boondockstitle">
		<h3>Boondocks Food & Fun</h3>
		<h4>2015-Current</h4>
	</div>
	<div id="boondockdes" data-aos="fade-up">
		<h4>Technician</h4>
		<p data-aos="fade-down">As a Technician my focus was mostly on repairing and updating arcade games and computers. Another part of the job was being a supervisor for the other attendants in the arcade. As a supervisor I was in charge of scheduling up breaks and making sure all employees were taken care of.</p>
	</div>
</div>
<br>
<br>
<div id="jobrush" data-aos="fade-up-left">
	<div id="rushdes" data-aos="fade-up">
		<h4>Supervisor</h4>
		<p data-aos="fade-up">As an arcade supervisor my job was to supervise a crew of 3-10 employees making sure that all daily tasks were being completed and guests were being taken care of. I also worked as a lead cashier leading a crew of 10-30 employees.</p>
	</div>
	<div id="rushtitle">
		<h3>The Rush Funplex</h3>
		<h4>2013-2015</h4>
	</div>
</div>

app/views/resume/homepage.html.erb
<div class="main parallax" id="mainparallax">
	<%= render "mainpage" %>
</div>
<div class="about parallax" id="aboutparallax">
	<%= render "about_me" %>
</div>
<div class="workexp parallax" id="workparallax">
	<%= render "work_experience" %>
</div>
<div class="experience parallax" id="expparallax">
	<%= render "experience" %>
</div>
<div class="portfolio parallax" id="portparallax">
	<%= render "example_work" %>
</div>
<div class="education parallax" id="eduparallax">
	<%= render "education" %>
</div>
<div class="contact parallax" id="contactparallax">
	<%= render "contact" %>
</div>